# local path
lmd:
  full: '/home/ashar/Documents/ece6254/project/data/lmd_genre/lmd_full/'
  # matched: '/home/ashar/Documents/ece6254/project/data/lmd_genre/'

lpd:

  full: '/home/ashar/Documents/ece6254/project/data/lmd_genre/lpd/'
  # matched: '/home/ashar/Documents/ece6254/project/data/lmd_genre/lpd/matched/'
  # full: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_full/'
  # matched: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_matched/'
  cleansed: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_cleansed/'

lpd-5:
  full: '/home/ashar/Documents/ece6254/project/data/lpd_5/full/'
  matched: '/home/ashar/Documents/ece6254/project/data/lpd_5/full/'

  #full: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_5_full/'
  #matched: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_5_matched/'
  cleansed: '/home/ashar/Documents/ece6254/project/data/lpd_5/cleansed/'

musicigan:
    full: '## Directory which has the full dataset'


match_scores: '/home/ashar/Downloads/match_scores.json'
midi_dict: '/home/ashar/Downloads/midis.json'

# parameters
multicore: 30 # 1 for disable multiprocessing, >1 to enable multiprocessing
beat_resolution: 24 # resolution of a beat (in time step)
time_signatures: ['4/4'] # '3/4', '2/4'
